[0]
Meter=String
MeterStyle=s
Text=short
LeftMouseDownAction=[!SetVariable dateformat "short" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables dateformat "short" "C:\Users\TB\Documents\Rainmeter\Skins\xClock\@Resources\variables.ini"][!SetOption dateformat_Select Text "short" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[1]
Meter=String
MeterStyle=s
Text=short day
LeftMouseDownAction=[!SetVariable dateformat "short day" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables dateformat "short day" "C:\Users\TB\Documents\Rainmeter\Skins\xClock\@Resources\variables.ini"][!SetOption dateformat_Select Text "short day" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[2]
Meter=String
MeterStyle=s
Text=short month
LeftMouseDownAction=[!SetVariable dateformat "short month" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables dateformat "short month" "C:\Users\TB\Documents\Rainmeter\Skins\xClock\@Resources\variables.ini"][!SetOption dateformat_Select Text "short month" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[3]
Meter=String
MeterStyle=s
Text=large
LeftMouseDownAction=[!SetVariable dateformat "large" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables dateformat "large" "C:\Users\TB\Documents\Rainmeter\Skins\xClock\@Resources\variables.ini"][!SetOption dateformat_Select Text "large" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[4]
Meter=String
MeterStyle=s
Text= ES_large
LeftMouseDownAction=[!SetVariable dateformat " ES_large" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables dateformat " ES_large" "C:\Users\TB\Documents\Rainmeter\Skins\xClock\@Resources\variables.ini"][!SetOption dateformat_Select Text " ES_large" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
